name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install sphinx pytest pytest-cov

    - name: Build Sphinx documentation
      run: |
        source .venv/bin/activate
        sphinx-apidoc -o docs/source src
        sphinx-build -b html docs/source docs/build

    - name: Run unit tests
      run: |
        source .venv/bin/activate
        pytest --cov=src --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./coverage.xml

    - name: Deploy documentation to GitHub Pages
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
        rsync -av --delete docs/build/ gh-pages/
        cd gh-pages
        git add .
        git commit -m "Update documentation"
        git push origin gh-pages